repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: docker-pytest
        name: docker pytest
        entry: docker compose run --rm api uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
